import type { Metadata } from "next";
import "./globals.css";
import SideNav from '@/src/app/components/SideNav';
import DayTracker from "@/src/app/components/DayTracker";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className="bg-grayCustom-500">
          <div className="flex">
              <div className="flex h-screen flex-col md:flex-row md:overflow-hidden w-[80%]">
                  <div className="w-full flex-none md:w-48">
                      <SideNav />
                  </div>

                  <div className="md:pd-12 flex-grow p-6 md:overflow-y-auto">
                      {children}
                  </div>
              </div>
              <div className="absolute right-10 top-10">
                  <DayTracker/>
              </div>

          </div>


      </body>

      </html>
  );
}
